# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='desciption',
            new_name='description',
        ),
    ]
